const events = {
    1: "reacted to your recent post",
    2: "followed you",
    3: "has joined your group",
    4: "sent you a private message",
    5: "commented on your picture",
    6: "left the group",
};

export const notifications = [
    {
        name: "Mark Webber",
        event: events[1],
        post: "My first tournament today!",
        group: "",
        message: "",
        read: false,
        duration: "1m ago",
    },
    {
        name: "Angela Gray",
        event: events[2],
        post: "",
        group: "",
        message: "",
        read: false,
        duration: "5m ago",
    },
    {
        name: "Jacob Thompson",
        event: events[3],
        post: "",
        group: "Chess Club",
        message: "",
        read: false,
        duration: "1 day ago",
    },
    {
        name: "Rizky Hasanuddin",
        event: events[4],
        post: "",
        group: "",
        message:
            "Hello, thanks for setting up the Chess Club. I've been a memeber for a few weeks now and I'm already having lots of fun and improving my game.",
        read: true,
        duration: "5 days ago",
    },
    {
        name: "Kimberly Smith",
        event: events[5],
        post: "",
        group: "",
        message: "",
        picture: "import picture to place here",
        read: true,
        duration: "1 week ago",
    },
    {
        name: "Nathan Peterson",
        event: events[1],
        post: "5 end-game strategies to increase your win rate",
        group: "",
        message: "",
        picture: "",
        read: true,
        duration: "2 weeks ago",
    },
    {
        name: "Anna Kim",
        event: events[6],
        post: "",
        group: "Chess Club",
        message: "",
        picture: "",
        read: true,
        duration: "2 weeks ago",
    },
];
